.build: &build
    stage: build
    image: docker:latest
    services:
        - docker:dind

build_container:
    <<: *build
    rules:
      - exists:
        - build/app/Dockerfile
    before_script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker pull -q ${CI_REGISTRY_IMAGE}
    script:
        - docker build -t ${CI_REGISTRY_IMAGE}:${DOCKER_TAG} -f build/app/Dockerfile .
        - docker push ${CI_REGISTRY_IMAGE}:${DOCKER_TAG}

build_database:
    <<: *build
    before_script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    rules:
      - exists:
        - build/database/Dockerfile
    script:
        - docker build -t ${CI_REGISTRY_IMAGE}/database:${DOCKER_TAG} -f build/database/Dockerfile build/database/
        - docker push ${CI_REGISTRY_IMAGE}/database:${DOCKER_TAG}
